### PR TITLE
Add compiled binaries to GitHub releases

### PR DESCRIPTION
**Pull request by lwthiker**

### CODE REVIEW

**Comment by momala454** [comment]
do you plan to add precompiled libcurl ?

**Comment by adesigner2** [comment]
Just deployed and tested it — work perfectly. How is it possible to use in php over curl?

**Comment by momala454** [comment]
> 

follow the steps from here https://github.com/lwthiker/curl-impersonate

```
Using CURL_IMPERSONATE env var

Experimental: If your application uses libcurl already, you can replace the existing library at runtime with LD_PRELOAD (Linux only). You can then set the CURL_IMPERSONATE env var. For example:

LD_PRELOAD=/path/to/libcurl-impersonate.so CURL_IMPERSONATE=chrome98 my_app

The CURL_IMPERSONATE env var will cause curl_easy_impersonate() to be called automatically for any new curl handle created by curl_easy_init().

Note that the above will NOT WORK for curl itself because the curl tool overrides the TLS settings. Use the wrapper scripts instead.
```

you can either do this 
LD_PRELOAD=/path/to/libcurl-impersonate.so
or change the libcurl.so in your system

and you can either do
CURL_IMPERSONATE=chrome98
or do this on your php script: 
putenv('CURL_IMPERSONATE=chrome98');

**Comment by adesigner2** [comment]
> 



> follow the steps from here https://github.com/lwthiker/curl-impersonate

Thank you for pointing me out. 

In my particular case I would need to run all those things on macos — which required .dylib instead of .so. I didn't figure out how to adjust all script to get it.

**Comment by momala454** [comment]
i suppose it's the same, replace the .dylib with the one you compiled instead of replace the .so

**Comment by adesigner2** [comment]
I recompiled curl-impersonate on my mac, got .dylib files, and it works through curl_chrome98 and curl_ff98 now.

> Just note that on macOS there is no `LD_PRELOAD`. You can try using `DYLD_LIBRARY_PATH` instead to point to the location where libcurl-impersonate dylib file is. I didn't test it personally yet.

Yes, it is what I'm trying to do. But can't find proper documentation how to use / set DYLD_LIBRARY_PATH. It looks like DYLD_LIBRARY_PATH you can sen path to the folder where library located, but still can't figure out how to associated curl-impersonate with php by analogy with LD_PRELOAD.

I tried another option — to rewrite libcurl.dylib of installed curl version. But it appears that mac and brew are using own versions of installed curls. And there is no .dylib files for mac version of the curl, I see .tbd instead.

**Comment by adesigner2** [comment]
> Just note that on macOS there is no `LD_PRELOAD`. You can try using `DYLD_LIBRARY_PATH` instead to point to the location where libcurl-impersonate dylib file is. I didn't test it personally yet.

It is what I found it is working for me now. You need to run it in command line (terminal) of macos:

DYLD_PRINT_LIBRARIES=1 X=1 DYLD_INSERT_LIBRARIES=/usr/local/lib/libcurl-impersonate-chrome.dylib CURL_IMPERSONATE=chrome98 php

Also I set in source code before curl_init(): 
putenv('CURL_IMPERSONATE=chrome99');

Thank you for great library!

**Pull request merged**
