### PR TITLE
Added python example

### PR DESCRIPTION
**Pull request by h3adex**
Wrote documentation on how to use curl-impersonate with pycurl.

Thanks for the great project

### CODE REVIEW

**Comment by lwthiker** [comment]
Thanks, can you change the instructions to work without the Docker container? i.e. on any system where curl-impersonate is installed. I think a lot of people are now using it without the container.

**Comment by h3adex** [comment]
> Thanks, can you change the instructions to work without the Docker container? i.e. on any system where curl-impersonate is installed. I think a lot of people are now using it without the container.

Hi. I'll add an instruction for linux.

**Comment by Yohan146** [comment]
Hi, I'm facing issues when importing pycurl: no module name pycurl. So should I install pycurl first before doing this?

**Comment by h3adex** [comment]
> Thanks, can you change the instructions to work without the Docker container? i.e. on any system where curl-impersonate is installed. I think a lot of people are now using it without the container.

Hi, I found some spare time and I added a instruction for linux.

**Comment by ycq0125** [comment]
> > Thanks, can you change the instructions to work without the Docker container? i.e. on any system where curl-impersonate is installed. I think a lot of people are now using it without the container.
> 
> Hi, I found some spare time and I added a instruction for linux.

This is invalid. The native module does not support creating non-standard TLS options for curl-impersonate.
You should refer to https://github.com/ycq0125/pycurl

**Pull request closed without merging**
