### PR TITLE
Adds support for brotli content decoding

### LINKED ISSUE #1: No support for brotli on content-encoding
As part of the headers sent to the server, `accept-encoding: gzip, deflate, br` is included.

However, this curl only supports `deflate, gzip`, as such a server returning `content-encoding: br` will fail to decompress with a `--compressed` argument.

### PR DESCRIPTION
**Pull request by WeebDataHoarder**
Simple addition of `libbrotli-dev` package makes curl configure script autodetect support.

Fixes #1

### CODE REVIEW

**Comment by lwthiker** [comment]
Thanks, I didn't notice it was missing. Two things:
* Can you run `ldd` on the resulting binary? I was trying to compile what I could statically and would like to see if this adds another dependency.
* Do you have a website that I can test it against? I would like to see that the wrapper scripts still work with all different encodings (normal,gz,brotli).

**Comment by lwthiker** [comment]
Forget about the second bullet, apparently Google does : )

**Comment by WeebDataHoarder** [comment]
Cloudflare also does if necessary.

ldd results:
```
root@be9d07dab857:/build/out# ldd curl-impersonate 
	linux-vdso.so.1 (0x00007ffdd29b4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f87f40ef000)
	libbrotlidec.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f87f40e0000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f87f3ec2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f87f3ea1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f87f3ce0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f87f44bf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f87f3b5d000)
	libbrotlicommon.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f87f3b38000)
```

**Comment by WeebDataHoarder** [comment]
Btw, it might be good to default to having `--compressed` flag when calling the curl binary by default or add this in the notes, as it's necessary to decode such output

**Comment by lwthiker** [comment]
* I guess we can live with the brotli dependency, seems pretty standard nowadays.
* Adding `--compressed` by default is a good idea. At first I thought it might change the HTTP headers but after another check it doesn't. I'll add it in a separate PR.

**Pull request merged**
